# Image source code: https://github.com/axonasif/workspace-images/tree/tmp
# Also see: https://github.com/gitpod-io/workspace-images/issues/1071
image: axonasif/workspace-python@sha256:f5ba627a31505ea6cf100abe8e552d7ff9e0abd6ba46745b6d6dab349c001430

tasks:
  - name: Init project and run server
    init: |
      pip install -r requirements.txt

    command: |
      echo "please export OPENAI_API_KEY=xxx-your-key"
      echo "then run python kube-chat.py"
vscode:
  extensions:
    - ms-python.python
